### ISSUE TITLE
The map isn't displayed anymore

### ISSUE THREAD

**Issue by sraillard** [cedbossneo/openmower-gui#35]
When selecting the "Map" entry, there is a blank screen:
![image](https://github.com/cedbossneo/openmower-gui/assets/32952986/41ebe4ba-08a3-4559-ab8e-958324aab9e0)

In the container log, we can see these error (404) messages:
```
[GIN] 2024/04/30 - 11:35:47 | 404 |      33.315µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538182&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      23.167µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538181&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      20.778µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538182&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |       17.63µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538181&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |       32.13µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538182&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      14.612µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538180&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      13.741µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538183&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      16.741µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538181&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      16.019µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538180&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      35.038µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538183&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      30.574µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538183&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      19.167µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538180&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      27.649µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538184&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      18.167µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538179&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      14.797µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538184&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      35.704µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538179&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      13.056µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538179&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      14.834µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538184&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:47 | 404 |      32.593µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269091&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      21.556µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269090&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      23.649µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269091&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      21.297µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269090&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      33.056µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269092&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      32.408µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269089&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      67.871µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269092&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      21.889µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269089&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:47 | 404 |      22.722µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134545&y=93549&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |      34.408µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134545&y=93550&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |       30.63µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134546&y=93549&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |      23.982µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134544&y=93550&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |      28.556µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134546&y=93550&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |      31.945µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=134544&y=93549&z=18"
[GIN] 2024/04/30 - 11:35:47 | 404 |      12.278µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=67272&y=46775&z=17"
[GIN] 2024/04/30 - 11:35:47 | 404 |      79.668µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=67272&y=46774&z=17"
[GIN] 2024/04/30 - 11:35:47 | 404 |      49.779µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=67273&y=46774&z=17"
[GIN] 2024/04/30 - 11:35:47 | 404 |      31.686µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=67273&y=46775&z=17"
[GIN] 2024/04/30 - 11:35:47 | 404 |      26.926µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=33636&y=23387&z=16"
[GIN] 2024/04/30 - 11:35:47 | 404 |       32.26µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=16818&y=11693&z=15"
[GIN] 2024/04/30 - 11:35:47 | 404 |      28.056µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=8409&y=5846&z=14"
[GIN] 2024/04/30 - 11:35:47 | 404 |      25.315µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=4204&y=2923&z=13"
[GIN] 2024/04/30 - 11:35:47 | 404 |      36.927µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=2102&y=1461&z=12"
[GIN] 2024/04/30 - 11:35:47 | 404 |      35.112µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=1051&y=730&z=11"
[GIN] 2024/04/30 - 11:35:47 | 404 |       30.63µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=525&y=365&z=10"
[GIN] 2024/04/30 - 11:35:50 | 404 |      32.945µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538182&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      30.167µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538181&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      27.019µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538180&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      25.871µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538184&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      21.352µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538183&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      30.037µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538185&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      14.944µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538185&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      37.574µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538179&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      29.704µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538185&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |          29µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538185&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |          35µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269091&y=187098&z=19"
[GIN] 2024/04/30 - 11:35:50 | 404 |      25.908µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269090&y=187098&z=19"
[GIN] 2024/04/30 - 11:35:50 | 404 |      29.241µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269092&y=187098&z=19"
[GIN] 2024/04/30 - 11:35:50 | 404 |      33.371µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538178&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      22.408µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538178&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      27.148µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538178&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |       14.63µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538178&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:50 | 404 |      21.056µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269089&y=187098&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |     144.447µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538177&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      21.315µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538186&y=374199&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |       27.63µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538177&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      19.537µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538177&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      14.686µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538186&y=374200&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      12.852µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538186&y=374198&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      14.093µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538177&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      23.834µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=538186&y=374197&z=20"
[GIN] 2024/04/30 - 11:35:51 | 404 |      30.982µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269088&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |      79.001µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269088&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |      26.389µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269093&y=187099&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |      23.871µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269093&y=187100&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |       29.89µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269088&y=187098&z=19"
[GIN] 2024/04/30 - 11:35:51 | 404 |      33.593µs |    192.168.1.51 | GET      "/tiles/vt/lyrs=s,h&x=269093&y=187098&z=19"

```

**Comment by sraillard** [comment]
I have find a way to fix the issue:
- stop the gui service
- remove all files in /boot/openmower/db
- start the gui service

**Comment by DavidBoman** [comment]
I have the sam issue.

**Comment by sraillard** [comment]
is it possible to disable the mapbox display so we can at least see the mower path?

**Comment by olliewalsh** [comment]
Can try ghcr.io/olliewalsh/openmower-gui:master until @cedbossneo can fix this. This uses maplibre/maptiler instead of mapbox. You will need to create a free maptiler account (and unlike mapbox creditcard is not required) , get your api key then set it in as the env var MAP_API_KEY or via the setting page

**Comment by olliewalsh** [comment]
@sraillard by the way those 404 errors are not the issue, open debug console on chrome and can see 401 unauthorized errors from mapbox

**Comment by Pawel-sp9pw** [comment]
> olliewalsh

Where have to add api key?

**Comment by olliewalsh** [comment]
> Where have to add api key?

Depends on how you run it, set MAP_API_KEY in https://github.com/cedbossneo/openmower-gui/blob/master/README.md?plain=1#L50 or https://github.com/cedbossneo/openmower-gui/blob/master/docker-compose.yaml#L19

**Comment by Tsepatek** [comment]
Hi Olliewalsh,
Did I get it right?
I edited gui.serivice file and replaced cedbossneo with olliewalsh and added --env MAP_API_KEY=XXXXXXXXX \

I cannot get gui.service to start.

**Comment by Tsepatek** [comment]
Now I was able to start the service so I got it right. Thanks for this. I need to edit my map.

**Comment by sraillard** [comment]
Thank you @olliewalsh: I have tried your new version and the map is displayed!

Getting an API key was quite easy, I went tohttps://www.maptiler.com/, create a free account, then there is a menu where the API key can be copied.

Here are my quick notes if it can help to migrate:
```
- systemctl stop gui.service
- nano /etc/systemd/system/gui.service
  - Add this line with your API key: --env MAP_API_KEY=xxxx \
  - Replace the container name by ghcr.io/olliewalsh/openmower-gui:test
- systemctl daemon-reload
- systemctl start gui.service

**Comment by cedbossneo** [comment]
Fixed map token

**Comment by cedbossneo** [comment]
@olliewalsh Is maplibre better ? If yes, maybe we can merge your work

**Comment by Tsepatek** [comment]
> @olliewalsh Is maplibre better ? If yes, maybe we can merge your work

Hi, both of the maps are quite blurry at least in my home town view. Could it be possible to you some other layer than satellite?

**Comment by waffle-stomper** [comment]
@cedbossneo Is there a way I can manually trigger an Openmower GUI update? I've got an old install where the map is still broken

**Comment by sraillard** [comment]
to update: `podman pull ghcr.io/cedbossneo/openmower-gui:master`

**Comment by cblims** [comment]
Seems like the token is invalid again.
